kind: ConfigMap
apiVersion: v1
metadata:
  name: php-app-conf
data:
  default.conf: |
    server {
      listen  80 default_server;
      listen  [::]:80 default_server;
      root    /var/www/public;
      index index.php index.html index.htm;
      charset utf-8;
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options "nosniff";
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }
      location = /favicon.ico { access_log off; log_not_found off; }
      location = /robots.txt  { access_log off; log_not_found off; }
      location ~ \.php$ {
          try_files $uri /index.php =404;

          set $fastcgi_https $https;
          if ($http_x_forwarded_proto = 'https') {
              set $fastcgi_https 'on';
          }
          fastcgi_param HTTPS $fastcgi_https; # set $_SERVER['HTTPS']

          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
      location ~ /\.(?!well-known).* {
          deny all;
      }
    }
  .env: |
    APP_NAME=Laravel
    APP_ENV=local
    APP_KEY=base64:{{ randAlphaNum 32 | b64enc }}
    APP_DEBUG=true
    APP_URL=https://php.k8s.kuops.com
    
    LOG_CHANNEL=stack
    
    DB_CONNECTION=mysql
    DB_HOST={{ .Values.configmap.db_host }}
    DB_PORT=3306
    DB_DATABASE=voyager
    DB_USERNAME=mysql
    DB_PASSWORD=mysql
    
    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120
    
    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379
    
    MAIL_DRIVER=smtp
    MAIL_HOST=smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    
    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1
    
    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
