apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voyager.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "voyager.name" . }}
    helm.sh/chart: {{ include "voyager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "voyager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "voyager.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      initContainers:
        - name: php-init
          image: {{ .Values.initcontainer.image.repository }}:{{ .Values.initcontainer.image.tag }}
          imagePullPolicy: {{ .Values.initcontainer.pullPolicy }}
          command: ['/bin/sh', '-c']
          args:
            - 'cp -rp /code/* /var/www && cd /var/www && php artisan voyager:install --with-dummy'
          volumeMounts:
            - name: php-app
              mountPath: /var/www
            - name: conf
              mountPath: /var/www/.env
              subPath: .env
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: CONFIGMAP_MD5
              value: "2c3e25a9114751c0db311944c26d90a0"
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: conf
              mountPath: /var/www/.env
              subPath: .env
            - name: php-app
              mountPath: /var/www
        - name: php-fpm
          image: {{ .Values.phpfpm.image.repository }}:{{ .Values.phpfpm.image.tag }}
          imagePullPolicy: {{ .Values.phpfpm.image.pullPolicy }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: conf
              mountPath: /var/www/.env
              subPath: .env
            - name: php-app
              mountPath: /var/www
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: conf
          configMap:
            name: php-app-conf
        - name: php-app
          emptyDir: {}
