apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voyager.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "voyager.name" . }}
    helm.sh/chart: {{ include "voyager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "voyager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "voyager.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: php-init
          image: docker.k8s.kuops.com/php-example-app:master-54
          command: ['/bin/sh', '-c']
          args:
            - 'cp -rp /code/* /var/www && cd /var/www && php artisan voyager:install --with-dummy'
          volumeMounts:
            - name: php-app
              mountPath: /var/www
            - name: conf
              mountPath: /var/www/.env
              subPath: .env
      containers:
        - name: nginx
          image: kuopsme/nginx:1.15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          env:
            - name: CONFIGMAP_MD5
              value: "2c3e25a9114751c0db311944c26d90a0"
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: conf
              mountPath: /var/www/.env
              subPath: .env
            - name: php-app
              mountPath: /var/www
        - name: php-fpm
          image: kuopsme/php:7.2-fpm-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: conf
              mountPath: /var/www/.env
              subPath: .env
            - name: php-app
              mountPath: /var/www
          resources:
            requests:
              memory: 128Mi
              cpu: 0.2
            limits:
              memory: 256Mi
              cpu: 0.5
      volumes:
        - name: conf
          configMap:
            name: php-app-conf
        - name: php-app
          emptyDir: {}
