# Default values for voyager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

initcontainer:
  image:
    repository: kuops/php-example-app
    tag: master
    pullPolicy: Always

phpfpm:
  image:
    repository: kuops/php
    tag: 7.4-fpm
    pullPolicy: IfNotPresent

nginx:
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

configmap:
  php_conf:
    app_url: php.app.{.INGRESS_NODE_IP}.nip.io
    db_host: example-mysql

resources: 
  limits:
   cpu: 0.5
   memory: 256Mi
  requests:
   cpu: 0.2
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
