# Default values for voyager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

initcontainer:
  image:
    repository: docker.k8s.kuops.com/php-example-app
    tag: master-54
    pullPolicy: Always

phpfpm:
  image:
    repository: kuopsme/php
    tag: 7.2-fpm-alpine
    pullPolicy: IfNotPresent

nginx:
  image:
    repository: kuopsme/nginx
    tag: 1.15-alpine
    pullPolicy: IfNotPresent

imagePullSecrets:
  name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - php.k8s.kuops.com
  tls:
    - secretName: php-tls-certs
      hosts:
        - php.k8s.kuops.com

configmap:
  name: php-app-conf
  db_host: mysql-dev

resources: 
  limits:
   cpu: 0.5
   memory: 256Mi
  requests:
   cpu: 0.2
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
